[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm run build:prod"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
