import React from "react";
import { FileDown, Download, BarChart3, PieChart, FileText } from "lucide-react";
import { useListDashboardReports } from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDate } from "@/lib/format";

const typeIcon: Record<string, React.ElementType> = {
  "Monthly Report":      FileText,
  "Quarterly Report":    BarChart3,
  "PPC Report":          PieChart,
  "Competitor Analysis": BarChart3,
};

export default function DashboardReports() {
  const { data: reports, isLoading } = useListDashboardReports();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-display font-bold tracking-tight">Reports</h1>
        <p className="text-muted-foreground mt-1">Download your performance reports and analytics.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Available Reports</CardTitle>
          <CardDescription>All reports generated by your account management team.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-4">{Array(4).fill(0).map((_, i) => <Skeleton key={i} className="h-20 w-full" />)}</div>
          ) : reports && reports.length > 0 ? (
            <div className="space-y-3">
              {reports.map(report => {
                const Icon = typeIcon[report.reportType] ?? FileDown;
                return (
                  <div key={report.id} className="flex items-start gap-4 p-4 rounded-lg border bg-card hover:border-primary/30 transition-colors group">
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center text-primary shrink-0">
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <p className="font-medium text-sm">{report.title}</p>
                          <p className="text-xs text-muted-foreground mt-0.5 line-clamp-2">{report.description}</p>
                          <div className="flex items-center gap-2 mt-2">
                            <Badge variant="secondary" className="text-xs">{report.reportType}</Badge>
                            <span className="text-xs text-muted-foreground">{report.period}</span>
                            <span className="text-xs text-muted-foreground">·</span>
                            <span className="text-xs text-muted-foreground">{formatDate(report.createdAt)}</span>
                          </div>
                        </div>
                        {report.fileUrl ? (
                          <Button variant="outline" size="sm" className="shrink-0" asChild>
                            <a href={report.fileUrl} target="_blank" rel="noreferrer">
                              <Download className="h-3.5 w-3.5 mr-1.5" />
                              PDF
                            </a>
                          </Button>
                        ) : (
                          <Button variant="outline" size="sm" className="shrink-0" disabled>
                            <Download className="h-3.5 w-3.5 mr-1.5" />
                            PDF
                          </Button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-16 border rounded-lg border-dashed">
              <FileDown className="h-8 w-8 text-muted-foreground/40 mb-3" />
              <p className="text-muted-foreground">No reports available yet.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
